### ISSUE TITLE
Error in BBox displayed in dataset map

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-spatial#112]
@FuhuXia Unfortunately your patch in #100 causes other bboxes to be badly displayed, check eg

http://demo.ckan.org/dataset/afghanistan-election-data

![yabdhi7](https://cloud.githubusercontent.com/assets/200230/8872866/0706e2da-31f9-11e5-8a61-39ea97f0e487.png)

Could you see if you can find the problem? Thanks

**Comment by FuhuXia** [comment]
The code made an assumption that the sequence of polygon bbox coordinates is from min-longitude to max-longitude, (ie, left to right). The issue occurs when coordinates are given the other way around. I will change the code so that it only deals with bbox that starts with positive longitude and ends with negative longitude, to minimize the impact, therefore it wont affect dataset like this.

**Comment by amercader** [comment]
Brilliant, thanks

**Comment by amercader** [comment]
Fixed in #113
