### ISSUE TITLE
Current used Default Basemap is not going to be avaliable from 31. October 

### ISSUE THREAD

**Issue by MarijaKnezevic** [ckan/ckanext-spatial#317]
Currently used basemap ([Stamen Terrain](https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html#stamen-terrain)) is not going to be avaliable from 31. October 2023 (see attached image).

![Stamen-backgroundmap](https://github.com/ckan/ckanext-spatial/assets/93824048/38e26d92-595a-4a5d-922a-b6f340039e02)

Could it be updated so that by default the other basemap is used? (e.g. [OpenStreetMap](https://wiki.openstreetmap.org/wiki/Raster_tile_providers) `https://tile.openstreetmap.org/${z}/${x}/${y}.png` ; [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/) or some other map)?

**Comment by amercader** [comment]
The bottom line is that currently there is no service that we can add as default that won't require some form of configuration by the user, which was the main selling point of the Stamen tiles. My plan going forward is to:

1. Not set any background tiles by default and clearly mark to the user that they should (see below)
2. Make really easy to choose and configure a provider, rather than the current cumbersome config system. For this I'll integrate the [leaflet-providers](https://github.com/leaflet-extras/leaflet-providers) plugin so we can add any of the [providers they support](https://leaflet-extras.github.io/leaflet-providers/preview/) with just two/three config options (type and API key)
3. Keep existing options for backwards compatibility.

It's nice to get a map with zero config but sadly that's no longer possible, so I think that's the best experience for new users.
I'll send a PR briefly.

![Screenshot 2023-10-26 at 12-57-05 Dataset - CKAN](https://github.com/ckan/ckanext-spatial/assets/200230/80bdb303-72e9-41fb-9cff-0f7e4048e100)

**Comment by amercader** [comment]
I just released ckanext-spatial 2.1.0 which adds support for may different tile providers via [Leaflet-providers](https://github.com/leaflet-extras/leaflet-providers). Please check the documentation for details on how to configure your map widgets and avoid the Stamen error tiles when using the old default tiles:

https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html

**Comment by amercader** [comment]
@mmdolbow no need to apologize, it's easy to get confused by this!

All CKAN settings, including the `ckanext.spatial.*` ones should be placed inside the `[app:main]` section, i.e. before the `[loggers]` one in the ini file
